Run 0225_run04_bal_lowleakyrely terminated due to memory resources
Traceback (most recent call last):
  File "C:/Users/alex8/OneDrive/Dokument/GitHub/BDP_cGAN/train_cgan.py", line 564, in <module>
    train(g_model, d_model, gan_model, dataset, latent_dim, fid_model)
  File "C:/Users/alex8/OneDrive/Dokument/GitHub/BDP_cGAN/train_cgan.py", line 504, in train
    fid_samples_real = scale_images(fid_samples_real, (299,299,3))
  File "C:/Users/alex8/OneDrive/Dokument/GitHub/BDP_cGAN/train_cgan.py", line 194, in scale_images
    return asarray(images_list)
  File "C:\Program Files\Python38\lib\site-packages\numpy\core\_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
numpy.core._exceptions.MemoryError: Unable to allocate 2.56 GiB for an array with shape (2560, 299, 299, 3) and data type float32